Traceback (most recent call last):
  File "notes.py", line 17, in <module>
    raise Exception('this is an error message')
Exception: this is an error message
